# Generated by Django 5.2.6 on 2025-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pearlApp", "0002_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image to represent the category",
                null=True,
                upload_to="category_images/",
            ),
        ),
    ]
