# Generated by Django 5.2.6 on 2025-11-20 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pearlApp", "0004_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
